"""empty message

Revision ID: 40fbb1155fa5
Revises: f2afae477969
Create Date: 2022-08-18 20:44:55.916490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fbb1155fa5'
down_revision = 'f2afae477969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'phone')
    op.drop_column('artists', 'phone')
    # ### end Alembic commands ###
