"""empty message

Revision ID: ddf3ab38634b
Revises: c8f1fc58b5c8
Create Date: 2022-08-18 03:50:39.283670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf3ab38634b'
down_revision = 'c8f1fc58b5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=500), nullable=False))
    op.drop_column('artists', 'website_link')
    op.add_column('venues', sa.Column('website', sa.String(length=500), nullable=False))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('venues', 'website')
    op.add_column('artists', sa.Column('website_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
