"""empty message

Revision ID: f2afae477969
Revises: 6a9d643e6b69
Create Date: 2022-08-18 20:43:17.266546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2afae477969'
down_revision = '6a9d643e6b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'phone')
    op.drop_column('venues', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
